// Site logo. Uses the logo set in Admin -> Settings -> Branding, otherwise the default "ht" mark
// (transparent PNG generated by scripts/make-logo-assets.ps1).
const DEFAULT = "/logo-mark.png";

export default function Logo({ src, className = "h-8" }) {
  const custom = src && src.trim() && src.trim() !== DEFAULT;
  return custom ? (
    <img src={src.trim()} alt="" aria-hidden="true" className={`w-auto max-w-[9rem] object-contain shrink-0 ${className}`} />
  ) : (
    <img src={DEFAULT} alt="" aria-hidden="true" width="318" height="256" style={{ aspectRatio: "318 / 256" }} className={`w-auto shrink-0 ${className}`} />
  );
}
