// Every piece of editable page text, in one place.
// - Admin -> Page Content is generated from CONTENT_PAGES.
// - The site reads the values through getSettings() (see lib/settings.js); the strings below are the defaults.
// - A field cleared in the admin falls back to its default.
//
// Field tuple: [key, label, default, type?, hint?]   type: "text" (default) | "textarea" | "image"
// Text tricks used by <RichText>: *word* highlights in the brand colour, {price} {name} {commission} are filled in.

const f = (key, label, def, type = "text", hint = "") => [key, label, def, type, hint];

const HL = "Wrap words in *stars* to highlight them.";

export const CONTENT_PAGES = [
  {
    id: "home",
    label: "Home page",
    groups: [
      {
        title: "Hero (top of the page)",
        fields: [
          f(
            "announcement",
            "Top badge text (one phrase per line)",
            "Enterprise-grade security",
            "textarea",
            "Add more than one line and the badge will type it out, pause, erase it and move to the next line on a loop - e.g. \"Enterprise-grade security\", \"24/7 Expert Support\", \"Instant Access After Payment\". A single line just types once and stays."
          ),
          f("heroTitleA", "Headline: start", "Premium Tools Made"),
          f("heroHighlight", "Headline: highlighted word", "Affordable"),
          f("heroTitleB", "Headline: end", "& Accessible"),
          f("heroText", "Paragraph under the headline", "Access premium SEO, design and AI tools like Ahrefs, SEMrush and Canva Pro at a fraction of the cost. Boost your rankings, analyze competitors and dominate search results with one toolkit.", "textarea"),
          f("heroImage", "Hero image (leave empty for the default artwork)", "", "image"),
          f("heroCta1", "Button 1 label", "Bulk Package pricing"),
          f("heroCta2", "Button 2 label", "Single tools Pricing"),
          f("heroPriceBadge", "Floating price badge", "From *{price}*/month", "text", "{price} is the cheapest tool price. " + HL),
          f("perk1Title", "Feature 1: title", "Premium SEO Tools"),
          f("perk1Body", "Feature 1: text", "Ahrefs, SEMrush, Moz Pro & more"),
          f("perk2Title", "Feature 2: title", "Affordable Pricing"),
          f("perk2Body", "Feature 2: text", "Save thousands vs individual tools"),
          f("perk3Title", "Feature 3: title", "24/7 Support"),
          f("perk3Body", "Feature 3: text", "Expert help when you need it"),
        ],
      },
      {
        title: "Hero popup panels (opened by the two hero buttons)",
        fields: [
          f("hpToolsTitle", "Tools panel: heading", "Single tools"),
          f("hpToolsSub", "Tools panel: sub heading", "{count} tools · pick what you need", "text", "{count} is the number of tools."),
          f("hpSearch", "Tools panel: search placeholder", "Search tools..."),
          f("hpAll", "Tools panel: 'All' chip", "All"),
          f("hpNoResults", "Tools panel: nothing found text", "No tools match your search."),
          f("hpFullPage", "Tools panel: link to the full page", "Open the full tools page"),
          f("hpBundlesTitle", "Packages panel: heading", "Bulk packages"),
          f("hpBundlesSub", "Packages panel: sub heading", "Fixed packs and custom packs, monthly price"),
          f("hpTabFixed", "Packages panel: first tab", "Fixed packs"),
          f("hpTabCustom", "Packages panel: second tab", "Custom packs"),
          f("hpIncluded", "Packages panel: 'tools included' link", "{count} tools included", "text", "{count} is the number of tools in the pack."),
          f("hpWhatYouGet", "Packages panel: custom pack link", "What you get"),
          f("hpPopular", "Packages panel: popular tag", "Popular"),
          f("hpBuyBtn", "Packages panel: buy button", "Get instant access"),
          f("hpAdd", "Add button", "Add"),
          f("hpAdded", "Added button", "Added"),
          f("hpEmptyCart", "Empty basket hint", "Add items to your basket, then checkout in one go."),
          f("hpCheckout", "Checkout bar label", "Checkout"),
        ],
      },
      {
        title: "Scrolling tool-name strip",
        fields: [f("marqueeLabel", "Small label above the strip", "Instant access to tools like")],
      },
      {
        title: "Single tools section",
        fields: [
          f("toolsTitle", "Heading", "Premium Tools Starting at *{price}*/Month", "text", "{price} is the cheapest tool price (like ৳239). " + HL),
          f("toolsSubtitle", "Sub heading", "Get instant access to enterprise-grade tools at up to 95% off retail prices."),
          f("toolCardBtn", "Tool card button", "Get Access"),
          f("toolsRequestText", "Text under the grid", "Need a specific tool not listed? We add new premium tools monthly based on user requests.", "textarea"),
          f("toolsViewAllBtn", "'View all' button", "View All Tools"),
          f("toolsRequestBtn", "'Request a tool' button", "Request New Tool - Free"),
          f("reqTitle", "Request popup: heading", "Request a new tool"),
          f("reqText", "Request popup: text", "Tell us which tool you need and chat with us directly. We add new tools based on your requests.", "textarea"),
          f("reqPlaceholder", "Request popup: input placeholder", "Tool name (optional)"),
          f("reqWhatsappBtn", "Request popup: WhatsApp button", "Chat on WhatsApp"),
          f("reqMessage", "Request popup: WhatsApp message", "Hi! I would like to request a new tool: {tool}", "text", "{tool} is what the customer typed in the popup."),
          f("reqOtherLabel", "Request popup: other channels label", "or reach us on"),
          f("reqFormLink", "Request popup: form link", "Prefer a call back? Leave your details"),
          f("reqChooseLabel", "Request popup: 'choose' label", "Choose how to reach us"),
          f("reqPreviewLabel", "Request popup: message preview label", "Your message"),
        ],
      },
      {
        title: "Bundles section",
        fields: [
          f("bundlesTitle", "Heading", "Save Thousands Annually with Premium Tool Bundles", "text", HL),
          f("bundlesSubtitle", "Sub heading", "Get premium SEO tools like Ahrefs, SEMrush and Moz Pro at up to 90% off retail prices.", "textarea"),
          f("bundlesLead", "Line above the cards", "Fixed Packs with Most Popular Tools - Instant Access"),
          f("bundlePopular", "'Most popular' ribbon", "Most Popular"),
          f("bundleViewLabel", "'View tools' link", "View included tools"),
          f("bundleHideLabel", "'Hide tools' link", "Hide included tools"),
          f("bundleBtn", "Card button", "Get Instant Access"),
        ],
      },
      {
        title: "Custom pack section",
        fields: [
          f("customTitle", "Heading", "Make your own pack by selecting tools ..."),
          f("customSubtitle", "Sub heading", "You can select any tools which you need and make a pack"),
          f("planPopular", "'Popular' ribbon", "Popular!"),
          f("planNote", "Small note in each card", "No hidden fees"),
          f("planBtn", "Card button", "Get Started"),
          f("customFooterText", "Text under the cards", "These packs don't suit you and you need a custom package? We understand and value your needs.", "textarea"),
          f("customBtn", "Quote button", "Quote for custom pack"),
          f("quoteTitle", "Quote popup: heading", "Get a custom pack quote"),
          f("quoteText", "Quote popup: text", "Tell us which tools you need and we will send you a price. Chat with us directly.", "textarea"),
          f("quotePlaceholder", "Quote popup: input placeholder", "Which tools do you need? (optional)"),
          f("quoteMessage", "Quote popup: WhatsApp message", "Hi! I would like a quote for a custom pack: {tool}", "text", "{tool} is what the customer typed in the popup. The WhatsApp button, other-channels label and call-back link use the wording from the 'Single tools section'."),
        ],
      },
      {
        title: "Demo section",
        fields: [
          f("demoBadge", "Badge", "Free Demo • No Credit Card Required"),
          f("demoTitle", "Heading", "Unleash the power of *Premium SEO Tools*", "text", HL),
          f("demoText", "Paragraph", "Explore our platform to understand how it functions, ensuring it meets your needs effectively. Or check the demo video first.", "textarea"),
          f("demoBtn1", "Button 1 label", "Start Free Demo Now"),
          f("demoBtn2", "Button 2 label", "Watch Demo"),
          f("demoUrl", "Demo video link (button 2). Empty = contact section", ""),
          f("demoPoint1", "Point 1", "No Credit Card Required"),
          f("demoPoint2", "Point 2", "Cancel Anytime"),
          f("demoPoint3", "Point 3", "Money Back Guarantee"),
          f("demoCard1Title", "Card 1: title", "SEO Analysis"),
          f("demoCard1Body", "Card 1: text", "Comprehensive keyword research and competitor analysis"),
          f("demoCard1Tags", "Card 1: tags (comma separated)", "SEMrush, Ahrefs, Moz Pro, +50 more"),
          f("demoCard2Title", "Card 2: title", "Analytics & Tracking"),
          f("demoCard2Body", "Card 2: text", "Advanced performance monitoring and reporting"),
          f("demoCard2Tags", "Card 2: tags (comma separated)", "Woorank, Seositecheckup, +30 more"),
          f("demoCard3Title", "Card 3: title", "Content Creation"),
          f("demoCard3Body", "Card 3: text", "AI-powered content and design tools"),
          f("demoCard3Tags", "Card 3: tags (comma separated)", "ChatGPT Business, Canva Pro, Grammarly, +10 more"),
          f("demoCard4Title", "Card 4: title", "Video AI"),
          f("demoCard4Body", "Card 4: text", "Create studio level video with AI"),
          f("demoCard4Tags", "Card 4: tags (comma separated)", "RunwayML, Midjourney, Google Veo, +50 more"),
        ],
      },
      {
        title: "Numbers (count-up counters)",
        fields: [
          f("statTools", "Tools count", "193+", "text", "Numbers count up on screen. Keep a suffix like + or %."),
          f("statLabelTools", "Tools label", "Premium Tools"),
          f("statUptime", "Uptime", "99.7%"),
          f("statLabelUptime", "Uptime label", "Uptime Guarantee"),
          f("statCustomers", "Customers", "9K+"),
          f("statLabelCustomers", "Customers label", "active customers"),
          f("statFastValue", "Fourth counter value", "Fast"),
          f("statFastLabel", "Fourth counter label", "Lightning Fast Performance"),
          f("statYears", "Years in service", "9+ years"),
        ],
      },
      {
        title: "Trust section",
        fields: [
          f("trustBadge", "Badge", "100% Secure Payment"),
          f("trustTitle", "Heading", "Wondering if you can trust us?", "text", HL),
          f("trustText", "Paragraph", "Every order is verified by a human before delivery, and every payment is backed by our refund promise.", "textarea"),
          f("trust1Title", "Card 1: title", "100% Fraud Protection"),
          f("trust1Body", "Card 1: text", "Advanced escrow-style handling ensures your money is protected until service delivery.", "textarea"),
          f("trust2Title", "Card 2: title", "Service Guarantee"),
          f("trust2Body", "Card 2: text", "If no service is received or a tool is non-functioning, a refund is processed within 24 hours after you report it.", "textarea"),
          f("trust3Title", "Card 3: title", "Registered Company"),
          f("trustNote", "Card 3: text (company details)", "Registered business. Details available on request.", "textarea"),
        ],
      },
      {
        title: "'Why choose us' comparison",
        fields: [
          f("whyTitle", "Heading", "Why Choose {name}?", "text", "{name} is your site name. " + HL),
          f("whySubtitle", "Sub heading", "See how we stack up against the competition"),
          f("whyGoodTitle", "Left chart: title", "{name} Performance"),
          f("whyGoodSub", "Left chart: sub title", "Customer satisfaction levels"),
          f("whyGoodFooter", "Left chart: footer", "Consistently exceeding expectations"),
          f("whyBadTitle", "Right chart: title", "Other Providers"),
          f("whyBadSub", "Right chart: sub title", "Average market performance"),
          f("whyBadFooter", "Right chart: footer", "Below industry standards"),
          f("whyMetrics", "Bar names (4, comma separated)", "Customer Satisfaction, Response Time, Tool Quality, Support Rating"),
          f("whyOurs", "Your bar values (4 numbers 0-100)", "98, 95, 97, 96", "text", "Illustrative sample values. Use real, verifiable numbers."),
          f("whyOthers", "Others' bar values (4 numbers 0-100)", "66, 45, 58, 52", "text", "Illustrative sample values. Use real, verifiable numbers."),
          f("whyStat1Label", "Box 1 label (value = Years in service)", "in this service field"),
          f("whyStat2Value", "Box 2 value", "24/7"),
          f("whyStat2Label", "Box 2 label", "Support Available"),
          f("whyStat3Label", "Box 3 label (value = Tools count)", "Premium Tools"),
          f("whyStat4Label", "Box 4 label (value = Uptime)", "Uptime Guarantee"),
        ],
      },
      {
        title: "Reviews section",
        fields: [
          f("reviewsTitle", "Heading", "What Our Customers Say", "text", HL),
          f("reviewsSubtitle", "Sub heading", "Real feedback from real customers"),
          f("reviewsFbTitle", "First row title", "Facebook Reviews"),
          f("reviewsTpTitle", "Second row title", "Trustpilot Reviews"),
        ],
      },
      {
        title: "Guarantee section",
        fields: [
          f("guaBadge", "Badge", "Guaranteed Satisfaction"),
          f("guaTitle", "Heading", "Your Success is Our Priority"),
          f("guaText", "Paragraph", "We stand behind our service with ironclad guarantees. Your satisfaction is not just promised, it is guaranteed with our comprehensive support system.", "textarea"),
          f("gua1Title", "Card 1: title", "100% Satisfaction Guarantee"),
          f("gua1Body", "Card 1: text", "Any issue with your access is fixed or refunded."),
          f("gua1Foot", "Card 1: footer", "30-day support window"),
          f("gua2Title", "Card 2: title", "Quality Assurance"),
          f("gua2Body", "Card 2: text", "All tools are tested before they reach you."),
          f("gua2Foot", "Card 2: footer", "Verified before delivery"),
          f("gua3Title", "Card 3: title", "24/7 Support"),
          f("gua3Body", "Card 3: text", "Expert team available round the clock."),
          f("gua3Foot", "Card 3: footer", "Always available"),
        ],
      },
      {
        title: "FAQ section (questions are managed under FAQs)",
        fields: [
          f("faqTitle", "Heading", "Frequently Asked Questions"),
          f("faqSubtitle", "Sub heading", "Got questions? We've got answers. If you can't find what you're looking for, reach out to our support team.", "textarea"),
        ],
      },
    ],
  },
  {
    id: "tools",
    label: "All Tools page",
    groups: [
      {
        title: "Page header",
        fields: [
          f("toolsPageBadge", "Badge", "Premium Tools Collection"),
          f("toolsPageTitle", "Heading", "All Premium Tools"),
          f("toolsPageText", "Paragraph", "Access our complete collection of premium tools at up to 95% off retail prices. Professional-grade software for creators, marketers, and businesses.", "textarea"),
          f("toolsPageCheck1", "Tick 1", "Instant Access"),
          f("toolsPageCheck2", "Tick 2", "100% Satisfaction Guarantee"),
          f("toolsPageCheck3", "Tick 3", "Free Updates"),
        ],
      },
      {
        title: "Exclusive banner and search",
        fields: [
          f("exclusiveTag", "Banner tag", "Exclusive"),
          f("exclusiveText", "Banner text", "Check our *Personal Tools [Not shared]* — save thousands", "text", HL),
          f("toolsSearchPlaceholder", "Search box placeholder", "Search tools by name..."),
          f("orderBtn", "Tool card button", "Order Now"),
        ],
      },
    ],
  },
  {
    id: "prompts",
    label: "AI Prompt Vault page",
    groups: [
      {
        title: "Page header (when the vault is ON)",
        fields: [
          f("pvMetaTitle", "Browser tab title", "AI Prompt Vault"),
          f("pvBadge", "Badge", "AI Prompt Vault"),
          f("pvTitle", "Heading", "Steal our *best-performing* AI prompts", "text", HL),
          f("pvText", "Paragraph", "A growing library of tested prompts for ChatGPT, Midjourney and more. Tap any card, copy the prompt, and go.", "textarea"),
          f("pvSearchPlaceholder", "Search box placeholder", "Search prompts..."),
          f("pvAllChip", "'All categories' chip", "All"),
          f("pvEmpty", "When there are no prompts", "No prompts match your search yet. New prompts are added every week."),
        ],
      },
      {
        title: "Prompt cards",
        fields: [
          f("pvViewBtn", "Card button", "View prompt"),
          f("pvNewTag", "'New' tag (first 7 days)", "New"),
        ],
      },
      {
        title: "Prompt popup",
        fields: [
          f("pvUseWith", "Label above the tags", "Works great with"),
          f("pvCopyBtn", "Copy button", "Copy prompt"),
          f("pvCopiedBtn", "After copying", "Copied!"),
          f("pvCloseBtn", "Close button", "Close"),
        ],
      },
      {
        title: "'Coming soon' page (shown while the vault is switched off)",
        fields: [
          f("pvSoonBadge", "Badge", "Coming soon"),
          f("pvSoonTitle", "Heading", "The *AI Prompt Vault* is on its way", "text", HL),
          f("pvSoonText", "Paragraph", "We are building a library of tested AI prompts for ChatGPT, Midjourney and more. Leave your details and we will tell you the moment it opens.", "textarea"),
          f("pvSoonNotifyBtn", "Notify button", "Notify me when it launches"),
          f("pvSoonBackBtn", "Second button", "Browse tools"),
          f("pvSoonPoint1", "Teaser 1", "Ready-to-use ChatGPT prompts"),
          f("pvSoonPoint2", "Teaser 2", "Midjourney & image prompts"),
          f("pvSoonPoint3", "Teaser 3", "New prompts added every week"),
        ],
      },
    ],
  },
  {
    id: "affiliate",
    label: "Affiliate page",
    groups: [
      {
        title: "'Coming soon' page (shown while the program is switched off)",
        fields: [
          f("affSoonBadge", "Badge", "Coming soon"),
          f("affSoonTitle", "Heading", "Our *Affiliate Program* is launching soon", "text", HL),
          f("affSoonText", "Paragraph", "We are getting something big ready: earn commission by sharing our tools. Leave your details and we will tell you the moment it opens.", "textarea"),
          f("affSoonNotifyBtn", "Notify button", "Notify me when it launches"),
          f("affSoonBackBtn", "Second button", "Browse tools"),
          f("affSoonPoint1", "Teaser 1", "High commission on every sale"),
          f("affSoonPoint2", "Teaser 2", "Lifetime referral earnings"),
          f("affSoonPoint3", "Teaser 3", "Fast, simple payouts"),
        ],
      },
      {
        title: "Our other shops (scrolling strip on the 'Coming soon' page)",
        fields: [
          f("otherShops", "Shops: one per line as  Name | https://link | short description. Empty = section hidden", "", "textarea", "Example: Digital Store | https://example.com | Software and subscriptions"),
          f("shopsBadge", "Small label", "More from us"),
          f("shopsTitle", "Heading", "Explore our other shops"),
          f("shopsSub", "Sub heading", "The same team, more ways to get what you need."),
          f("shopsVisit", "Link text on each card", "Visit shop"),
        ],
      },
      {
        title: "Hero",
        fields: [
          f("affBadge", "Badge", "Affiliate Program"),
          f("affTitle", "Heading", "Earn Big with Our *Affiliate Program*", "text", HL),
          f("affText", "Paragraph", "Join thousands of successful affiliates earning up to {commission}% commission on every sale. Get lifetime referrals, performance bonuses, and professional marketing support.", "textarea", "{commission} is the max commission from Settings -> Affiliate program."),
          f("affBtnJoin", "Button 1 label", "Join Now - It's Free"),
          f("affBtnRates", "Button 2 label", "View Commission Rates"),
        ],
      },
      {
        title: "Benefits",
        fields: [
          f("affWhyTitle", "Heading", "Why Choose Our Affiliate Program?"),
          f("affWhySub", "Sub heading", "Industry-leading benefits and support to help you maximize your earnings"),
          f("affB1Title", "Benefit 1: title", "High Commission Rates"),
          f("affB1Body", "Benefit 1: text", "Earn up to {commission}% commission on every sale you refer."),
          f("affB2Title", "Benefit 2: title", "Lifetime Referrals"),
          f("affB2Body", "Benefit 2: text", "Earn from customers for their purchases with us as long as they have auto renewals."),
          f("affB3Title", "Benefit 3: title", "Performance Bonuses"),
          f("affB3Body", "Benefit 3: text", "Extra rewards for top-performing affiliates."),
          f("affB4Title", "Benefit 4: title", "Marketing Materials"),
          f("affB4Body", "Benefit 4: text", "Professional banners, links, and promotional content."),
        ],
      },
      {
        title: "Analytics section",
        fields: [
          f("affAnalyticsTitle", "Heading", "Affiliate Performance Analytics"),
          f("affAnalyticsSub", "Sub heading", "Track your earnings and performance with our comprehensive analytics dashboard"),
          f("affExampleNote", "Small disclaimer", "Figures below are illustrative examples, not guaranteed earnings."),
        ],
      },
      {
        title: "How it works",
        fields: [
          f("affHowTitle", "Heading", "How It Works"),
          f("affHowSub", "Sub heading", "Getting started is simple. Follow these four easy steps to begin earning"),
          f("affStep1Title", "Step 1: title", "Sign Up"),
          f("affStep1Body", "Step 1: text", "Join our affiliate program in minutes with a simple registration process"),
          f("affStep2Title", "Step 2: title", "Get Your Links"),
          f("affStep2Body", "Step 2: text", "Receive unique tracking links and promotional materials"),
          f("affStep3Title", "Step 3: title", "Promote"),
          f("affStep3Body", "Step 3: text", "Share our tools with your audience and network"),
          f("affStep4Title", "Step 4: title", "Earn Money"),
          f("affStep4Body", "Step 4: text", "Get paid commission for every successful referral"),
        ],
      },
      {
        title: "Bottom call to action",
        fields: [
          f("affCtaTitle", "Heading", "Ready to Start Earning?"),
          f("affCtaText", "Paragraph", "Join our affiliate program today and start earning commissions on every sale you refer.", "textarea"),
          f("affCtaBtn1", "Button 1 label", "Join Affiliate Program"),
          f("affCtaBtn2", "Button 2 label", "Contact Support"),
        ],
      },
    ],
  },
  {
    id: "offers",
    label: "Free Offers page",
    groups: [
      {
        title: "Page header (when the program is ON)",
        fields: [
          f("offersMetaTitle", "Browser tab title", "Free Offers"),
          f("offersBadge", "Badge", "Free for you"),
          f("offersTitle", "Heading", "Grab our *Free Offers*", "text", HL),
          f("offersText", "Paragraph", "Claim a free offer in seconds. No payment needed: just tell us where to send it.", "textarea"),
          f("offersEmpty", "When there are no offers", "No offers right now. Check back soon, new free offers are added often!"),
        ],
      },
      {
        title: "Offer cards",
        fields: [
          f("offersClaimBtn", "Claim button", "Claim for free"),
          f("offersSoldOut", "Fully claimed", "Fully claimed"),
          f("offersEnded", "Offer ended", "Offer ended"),
          f("offersLeft", "Spots left", "{left} left", "text", "{left} is the number of spots remaining."),
          f("offersEnds", "Ends line", "Ends {date}", "text", "{date} is the end date."),
          f("offersEndsIn", "Ends line when it is close", "Ends in {time}", "text", "Used in the last 7 days, counts down live."),
          f("offersClaimedCount", "People who claimed (no limit set)", "{n} claimed"),
          f("offersJoinClaim", "Default button when the offer has a channel to join", "Join & claim free"),
        ],
      },
      {
        title: "Claim popup",
        fields: [
          f("offersClaimTitle", "Heading", "Claim: {name}", "text", "{name} is the offer name."),
          f("offersFormNote", "Note under the heading", "Enter your details and your free offer appears right away."),
          f("offersJoinNote", "Note under the heading (offers with a channel)", "Join our channel, then unlock your free offer."),
          f("offersStep1", "Step 1 label", "Step 1: Join"),
          f("offersStep2", "Step 2 label", "Step 2: Get your offer"),
          f("offersJoinBtn", "Join button", "Join {channel}", "text", "{channel} becomes Telegram, WhatsApp, Facebook..."),
          f("offersChecking", "While checking", "Checking..."),
          f("offersJoined", "After joining", "Joined"),
          f("offersLocked", "Locked message", "Join first to unlock"),
          f("offersJoinTelegram", "Default text: Telegram", "Join our Telegram channel"),
          f("offersJoinWhatsapp", "Default text: WhatsApp", "Join our WhatsApp channel"),
          f("offersJoinFacebook", "Default text: Facebook", "Follow our Facebook page"),
          f("offersJoinInstagram", "Default text: Instagram", "Follow us on Instagram"),
          f("offersJoinYoutube", "Default text: YouTube", "Subscribe on YouTube"),
          f("offersJoinOther", "Default text: other link", "Visit our page"),
          f("offersFHandle", "Telegram/WhatsApp field placeholder", "Your Telegram username or WhatsApp number"),
          f("offersFName", "Name placeholder", "Your name"),
          f("offersFEmail", "Email placeholder", "Your email"),
          f("offersFPhone", "Phone placeholder", "Phone / WhatsApp (optional)"),
          f("offersSubmit", "Submit button", "Get my free offer"),
          f("offersSuccessTitle", "Success heading", "It's yours!"),
          f("offersYourOffer", "Label above the reward", "Your offer"),
          f("offersNoReward", "When the offer has no code/link (offer has a channel)", "We have received your request. Please message us on our {channel} channel to get your offer.", "text", "{channel} becomes Telegram, WhatsApp... (the first channel set on the offer)."),
          f("offersContactBtn", "Button that opens that channel", "Message us on {channel}"),
          f("offersNoRewardMail", "When the offer has no code/link and no channel", "We have received your request. We will contact you by email shortly."),
          f("offersAlready", "When they claim the same offer again", "You had already claimed this offer, here it is again."),
          f("offersOpen", "Open link button", "Open link"),
          f("offersCopy", "Copy button", "Copy"),
          f("offersCopied", "After copying", "Copied"),
          f("offersClose", "Close button", "Close"),
        ],
      },
      {
        title: "'Coming soon' page (shown while Free Offers is switched off)",
        fields: [
          f("offSoonBadge", "Badge", "Coming soon"),
          f("offSoonTitle", "Heading", "Free *Offers* are coming soon", "text", HL),
          f("offSoonText", "Paragraph", "We are preparing free offers, coupons and giveaways just for you. Leave your details and we will tell you the moment they go live.", "textarea"),
          f("offSoonNotifyBtn", "Notify button", "Notify me when it launches"),
          f("offSoonBackBtn", "Second button", "Browse tools"),
          f("offSoonPoint1", "Teaser 1", "Free coupons and discounts"),
          f("offSoonPoint2", "Teaser 2", "Surprise giveaways"),
          f("offSoonPoint3", "Teaser 3", "Claim in seconds, no payment"),
        ],
      },
    ],
  },
  {
    id: "limits",
    label: "Tool Limits page",
    groups: [
      {
        title: "Page header",
        fields: [
          f("limitsPageTitleMeta", "Browser tab title", "Tool Limits & Status"),
          f("limitsBadge", "Badge", "Live tool status"),
          f("limitsTitle", "Heading", "Tool *Limits* & Active Status", "text", HL),
          f("limitsText", "Paragraph", "Check which tools are working right now and what limits apply before you buy. Status is updated by our team.", "textarea"),
          f("limitsUpdated", "'Last updated' label", "Last updated:"),
          f("limitsFootnote", "Note at the bottom", "Limits are set by each tool's provider and can change. If a tool stops working, contact support and we will fix or replace it, or refund you.", "textarea"),
        ],
      },
      {
        title: "Status names",
        fields: [
          f("limitsLabelActive", "Active", "Active"),
          f("limitsLabelLimited", "Limited", "Limited"),
          f("limitsLabelMaintenance", "Maintenance", "Maintenance"),
          f("limitsLabelDown", "Down", "Down"),
        ],
      },
      {
        title: "Table",
        fields: [
          f("limitsSearch", "Search placeholder", "Search tools, categories..."),
          f("limitsShowing", "'Showing' line", "Showing {shown} of {total} tools", "text", "{shown} and {total} are filled in automatically."),
          f("limitsFilterAll", "Filter: all", "All"),
          f("limitsFilterShared", "Filter: shared", "Shared"),
          f("limitsFilterPrivate", "Filter: private", "Private"),
          f("limitsSortNameAsc", "Sort: name A-Z", "Name A–Z"),
          f("limitsSortNameDesc", "Sort: name Z-A", "Name Z–A"),
          f("limitsSortPriceAsc", "Sort: price low to high", "Price ↑"),
          f("limitsSortPriceDesc", "Sort: price high to low", "Price ↓"),
          f("limitsColNum", "Column: number", "#"),
          f("limitsColTool", "Column: tool", "Tool Name"),
          f("limitsColCategory", "Column: category", "Category"),
          f("limitsColType", "Column: type", "Type"),
          f("limitsColPrice", "Column: price", "Price"),
          f("limitsColLimit", "Column: description / limits", "Description / Limits"),
          f("limitsColBuy", "Column: buy", "Buy"),
          f("limitsPer", "Word before the duration", "per"),
          f("limitsSeeMore", "'See more' link", "See more"),
          f("limitsSeeLess", "'See less' link", "See less"),
          f("limitsNoLimit", "When a tool has no description or limit", "No limit"),
          f("limitsNone", "Nothing found", "No tools match."),
          f("limitsOrderBtn", "Order button", "Order"),
        ],
      },
    ],
  },
  {
    id: "other",
    label: "Checkout & footer",
    groups: [
      {
        title: "Checkout page",
        fields: [
          f("checkoutTitle", "Heading", "Checkout"),
          f("checkoutSub", "Sub heading", "Review your order, choose how you will pay, and confirm."),
        ],
      },
      {
        title: "Product quick view (Read more popup)",
        fields: [
          f("qvIncluded", "Heading above the list", "What is included"),
          f("qvPerks", "Default list (used when the product has no bullet points)", "Access for {duration}" + "\n" + "Verified before delivery" + "\n" + "Support if access stops working", "textarea", "One per line. {duration} is replaced by the product duration."),
          f("qvAdd", "Add to cart button", "Add to Cart"),
          f("qvAdded", "After adding", "Added to basket"),
          f("qvGoBasket", "Already in basket", "Go to checkout"),
          f("qvBuy", "Buy now button", "Buy now"),
          f("qvFull", "Link to the full page", "View full details"),
          f("qvTrust", "Small trust line", "Refund if access does not work. Delivered after payment verification."),
        ],
      },
      {
        title: "Coming soon products (popup and button)",
        fields: [
          f("soonBtn", "Button on a coming-soon product", "Coming soon"),
          f("soonBadge", "Badge on the product picture", "COMING SOON"),
          f("soonTitle", "Popup heading", "Coming soon"),
          f("soonText", "Popup text", "{name} is not available to order yet. Leave your details and we will tell you the moment it goes live.", "textarea", "{name} is the product name."),
          f("soonFName", "Name placeholder", "Your name"),
          f("soonFEmail", "Email placeholder", "Your email"),
          f("soonNotify", "Notify button", "Notify me"),
          f("soonThanks", "After sending", "Thanks! We will notify you as soon as it is available."),
          f("soonWaBtn", "WhatsApp button", "Ask on WhatsApp"),
          f("soonWaMsg", "WhatsApp message", "Hi! When will {name} be available?", "text", "{name} is the product name."),
        ],
      },
      {
        title: "Chat button (floating popup)",
        fields: [
          f("chatGreeting", "Greeting", "Hi 👋, How can we help today?"),
          f("chatOnline", "Online text", "We are online"),
          f("chatReply", "Reply time", "Replies in minutes"),
          f("chatTopicsLabel", "Topics label", "What do you need help with?"),
          f("chatTopic1", "Topic 1 button", "Order help"),
          f("chatTopic1Msg", "Topic 1 message", "Hi! I need help with my order."),
          f("chatTopic2", "Topic 2 button", "Pricing"),
          f("chatTopic2Msg", "Topic 2 message", "Hi! I would like to know about pricing."),
          f("chatTopic3", "Topic 3 button", "Request a tool"),
          f("chatTopic3Msg", "Topic 3 message", "Hi! I would like to request a tool."),
          f("chatFastTag", "Tag on WhatsApp (empty = none)", "Fastest"),
          f("chatBrowse", "Bottom button", "Browse tools"),
        ],
      },
      {
        title: "WhatsApp contact",
        fields: [
          f("waFooterLabel", "Footer: WhatsApp line", "WhatsApp"),
          f("waAskLabel", "Product page: button", "Ask on WhatsApp"),
          f("waProductMsg", "Product page: message", "Hi! I am interested in {tool} (৳{price}). Is it available?", "text", "{tool} and {price} are filled in."),
          f("waHelpMsg", "Checkout: 'need help' message", "Hi! I need help paying for my order: {items} (Total ৳{total}).", "text", "{items} and {total} are filled in."),
          f("waOrderBtn", "Order placed: button", "Send payment details on WhatsApp"),
          f("waOrderNote", "Order placed: small text above the button", "Send us your payment screenshot for faster confirmation."),
          f("waOrderMsg", "Order placed: message", "Hi! I placed order #{number}: {items} (৳{amount}). Payment: {method}, Transaction ID: {txn}.", "text", "{number} {items} {amount} {method} {txn} are filled in."),
          f("waAccountLabel", "My orders: help link", "WhatsApp"),
          f("waAccountMsg", "My orders: message", "Hi! I need help with order #{number}: {items}.", "text", "{number} and {items} are filled in."),
        ],
      },
      {
        title: "Footer",
        fields: [
          f("chanTitle", "Channels box: heading", "Exclusive coupons, giveaways, and premium tools, free."),
          f("chanText", "Channels box: paragraph", "Join our channels to get access to special coupons, giveaways and premium tools for free. Questions or a tool request? Message us here too.", "textarea"),
          f("footerCopyLine", "Copyright line (bottom of every page)", "© {year} {name}. All Rights Reserved. Premium Tools & Digital Marketing Solutions.", "text", "{year} changes by itself every January, {name} is your site name (Settings > General). You can write anything: wrap words in *stars* to colour them."),
          f("footerNote", "Extra small line under the copyright (optional)", "", "text", "For example a company number, a tagline or 'Made in Bangladesh'. Leave empty to hide it."),
          f("footerLinkPrivacy", "Bottom link 1: label", "Privacy"),
          f("footerLinkTerms", "Bottom link 2: label", "TOS"),
          f("footerLinkRefund", "Bottom link 3: label", "Refund Policy"),
        ],
      },
    ],
  },
];

export const CONTENT_DEFAULTS = Object.fromEntries(CONTENT_PAGES.flatMap((p) => p.groups.flatMap((g) => g.fields.map((x) => [x[0], x[2]]))));
export const CONTENT_KEYS = Object.keys(CONTENT_DEFAULTS);
