// Single source of truth for every admin-managed table.
// Used by the admin UI (forms/tables) AND the API (validation/coercion).
// type: text | textarea | number | bool | select | image | color | category | icon | status

export const ICONS = ["zap", "star", "palette", "pen", "graduation", "video", "bot", "tv", "crown", "gem", "shield", "search"];

export const RESOURCES = {
  tools: {
    model: "tool",
    title: "Tools",
    singular: "Tool",
    orderBy: [{ sort: "asc" }, { createdAt: "desc" }],
    search: ["name", "description"],
    slugFrom: "name",
    include: { category: true },
    fields: [
      { key: "name", label: "Name", type: "text", required: true, list: true },
      { key: "image", label: "Cover image", type: "image", list: "image" },
      { key: "categoryId", label: "Category", type: "category", list: "category" },
      { key: "price", label: "Price (৳)", type: "number", required: true, list: "money" },
      { key: "duration", label: "Duration", type: "text", def: "30 days", list: true },
      { key: "accent", label: "Cover accent color", type: "color", def: "#E8352B" },
      { key: "description", label: "Description (start a line with - to make a bullet point)", type: "textarea", required: true },
      { key: "sort", label: "Sort order", type: "number", def: 0 },
      { key: "featured", label: "Featured", type: "bool", list: "badge" },
      { key: "active", label: "Visible on site", type: "bool", def: true, list: "badge" },
      { key: "soon", label: "Coming soon", type: "soon", def: false, list: "soon" },
    ],
  },
  categories: {
    model: "category",
    title: "Categories",
    singular: "Category",
    orderBy: [{ sort: "asc" }],
    search: ["name"],
    slugFrom: "name",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, list: true },
      { key: "sort", label: "Sort order", type: "number", def: 0, list: true },
      { key: "active", label: "Visible", type: "bool", def: true, list: "badge" },
    ],
  },
  bundles: {
    model: "bundle",
    title: "Bundles",
    singular: "Bundle",
    orderBy: [{ sort: "asc" }],
    search: ["name", "tagline"],
    fields: [
      { key: "name", label: "Name", type: "text", required: true, list: true },
      { key: "tagline", label: "Tagline", type: "text", required: true, list: true },
      { key: "price", label: "Price (৳/month)", type: "number", required: true, list: "money" },
      { key: "icon", label: "Icon", type: "icon", def: "zap" },
      { key: "tools", label: "Included tools (one per line)", type: "textarea", required: true },
      { key: "sort", label: "Sort order", type: "number", def: 0 },
      { key: "popular", label: "Most popular", type: "bool", list: "badge" },
      { key: "active", label: "Visible", type: "bool", def: true, list: "badge" },
      { key: "soon", label: "Coming soon", type: "soon", def: false, list: "soon" },
    ],
  },
  plans: {
    model: "packPlan",
    title: "Custom Packs",
    singular: "Pack plan",
    orderBy: [{ sort: "asc" }],
    search: ["name"],
    fields: [
      { key: "name", label: "Name", type: "text", required: true, list: true },
      { key: "tagline", label: "Tagline", type: "text", required: true },
      { key: "price", label: "Price (৳/month)", type: "number", required: true, list: "money" },
      { key: "feature", label: "Feature line", type: "text", required: true, list: true },
      { key: "icon", label: "Icon", type: "icon", def: "star" },
      { key: "sort", label: "Sort order", type: "number", def: 0 },
      { key: "popular", label: "Popular", type: "bool", list: "badge" },
      { key: "active", label: "Visible", type: "bool", def: true, list: "badge" },
      { key: "soon", label: "Coming soon", type: "soon", def: false, list: "soon" },
    ],
  },
  prompts: {
    model: "prompt",
    title: "AI Prompt Vault",
    singular: "Prompt",
    orderBy: [{ sort: "asc" }, { createdAt: "desc" }],
    search: ["title", "category", "tags", "promptText"],
    slugFrom: "title",
    fields: [
      { key: "title", label: "Title", type: "text", required: true, list: true },
      { key: "image", label: "Cover image — square works best, e.g. 1080×1080 (leave empty to use a colour cover)", type: "image", list: "image" },
      { key: "accent", label: "Cover accent color (used when there is no image)", type: "color", def: "#E8352B" },
      { key: "category", label: "Category", type: "text", list: true },
      { key: "promptText", label: "The prompt (shown in the popup, with a Copy button)", type: "textarea", required: true },
      { key: "tags", label: "Works great with (comma separated, e.g. ChatGPT, Midjourney)", type: "text" },
      { key: "sort", label: "Sort order", type: "number", def: 0 },
      { key: "featured", label: "Featured", type: "bool", list: "badge" },
      { key: "active", label: "Visible on site", type: "bool", def: true, list: "badge" },
    ],
  },
  reviews: {
    model: "review",
    title: "Reviews",
    singular: "Review",
    orderBy: [{ sort: "asc" }],
    search: ["name", "text"],
    fields: [
      { key: "name", label: "Customer name", type: "text", required: true, list: true },
      { key: "source", label: "Source", type: "select", options: ["facebook", "trustpilot"], def: "facebook", list: true },
      { key: "rating", label: "Rating (1-5)", type: "number", def: 5, list: true },
      { key: "text", label: "Review", type: "textarea", required: true, list: true },
      { key: "sort", label: "Sort order", type: "number", def: 0 },
      { key: "active", label: "Visible", type: "bool", def: true, list: "badge" },
    ],
  },
  faqs: {
    model: "faq",
    title: "FAQs",
    singular: "FAQ",
    orderBy: [{ sort: "asc" }],
    search: ["question", "answer"],
    fields: [
      { key: "question", label: "Question", type: "text", required: true, list: true },
      { key: "answer", label: "Answer", type: "textarea", required: true },
      { key: "sort", label: "Sort order", type: "number", def: 0, list: true },
      { key: "active", label: "Visible", type: "bool", def: true, list: "badge" },
    ],
  },
  leads: {
    model: "lead",
    title: "Leads",
    singular: "Lead",
    orderBy: [{ createdAt: "desc" }],
    search: ["name", "email", "message"],
    noCreate: true,
    fields: [
      { key: "type", label: "Type", type: "readonly", list: true },
      { key: "name", label: "Name", type: "readonly", list: true },
      { key: "email", label: "Email", type: "readonly", list: true },
      { key: "phone", label: "Phone", type: "readonly" },
      { key: "message", label: "Message", type: "readonly", list: true },
      { key: "handled", label: "Handled", type: "bool", list: "badge" },
      { key: "createdAt", label: "Date", type: "readonly", list: "date" },
    ],
  },
  payouts: {
    model: "payout",
    title: "Payouts",
    singular: "Payout",
    orderBy: [{ createdAt: "desc" }],
    search: ["userName", "userEmail", "account"],
    noCreate: true,
    fields: [
      { key: "userName", label: "Affiliate", type: "readonly", list: true },
      { key: "userEmail", label: "Email", type: "readonly", list: true },
      { key: "amount", label: "Amount", type: "readonly", list: "money" },
      { key: "method", label: "Method", type: "readonly", list: true },
      { key: "account", label: "Account", type: "readonly", list: true },
      { key: "status", label: "Status", type: "status", options: ["PENDING", "PAID", "REJECTED"], def: "PENDING", list: "status" },
      { key: "createdAt", label: "Date", type: "readonly", list: "date" },
    ],
  },
  orders: {
    model: "order",
    title: "Orders",
    singular: "Order",
    orderBy: [{ createdAt: "desc" }],
    search: ["name", "email", "phone", "itemName", "txnId"],
    noCreate: true,
    fields: [
      { key: "number", label: "#", type: "readonly", list: "orderno" },
      { key: "itemName", label: "Item", type: "readonly", list: true },
      { key: "itemType", label: "Source", type: "readonly", list: "source" },
      { key: "amount", label: "Amount", type: "readonly", list: "money" },
      { key: "name", label: "Customer", type: "readonly", list: true },
      { key: "email", label: "Email", type: "readonly" },
      { key: "phone", label: "Phone", type: "readonly" },
      { key: "method", label: "Payment method", type: "readonly" },
      { key: "txnId", label: "Transaction ID", type: "readonly" },
      { key: "refCode", label: "Referred by (code)", type: "readonly" },
      { key: "commission", label: "Affiliate commission (৳)", type: "readonly" },
      { key: "status", label: "Status", type: "status", options: ["PENDING", "PAID", "DELIVERED", "REFUNDED", "CANCELLED"], def: "PENDING", list: "status" },
      { key: "note", label: "Customer note", type: "readonly" },
      { key: "createdAt", label: "Date", type: "readonly", list: "date" },
    ],
  },
};

export const NAV = [
  { href: "/admin", label: "Dashboard", icon: "dashboard" },
  { href: "/admin/orders", label: "Orders", icon: "orders" },
  { href: "/admin/sales", label: "Sales Report", icon: "sales" },
  { href: "/admin/analytics", label: "Analytics", icon: "analytics" },
  { href: "/admin/affiliates", label: "Affiliates", icon: "affiliates" },
  { href: "/admin/payouts", label: "Payouts", icon: "payouts" },
  { href: "/admin/free-offers", label: "Free Offers", icon: "offers" },
  { href: "/admin/prompts", label: "AI Prompt Vault", icon: "prompts" },
  { href: "/admin/leads", label: "Leads", icon: "leads" },
  { href: "/admin/tools", label: "Tools", icon: "tools" },
  { href: "/admin/tool-limits", label: "Tool Limits", icon: "limits" },
  { href: "/admin/categories", label: "Categories", icon: "categories" },
  { href: "/admin/bundles", label: "Bundles", icon: "bundles" },
  { href: "/admin/plans", label: "Custom Packs", icon: "plans" },
  { href: "/admin/reviews", label: "Reviews", icon: "reviews" },
  { href: "/admin/faqs", label: "FAQs", icon: "faqs" },
  { href: "/admin/content", label: "Page Content", icon: "content" },
  { href: "/admin/settings", label: "Settings", icon: "settings" },
];
