// Single source of truth for every admin-managed table.
// Used by the admin UI (forms/tables) AND the API (validation/coercion).
// type: text | textarea | number | decimal | bool | select | image | gallery | files | packages | color | category | icon | status
import { PRODUCT_KINDS, SERVICE_KINDS } from "./catalog";

export const ICONS = ["zap", "star", "palette", "pen", "graduation", "video", "bot", "tv", "crown", "gem", "shield", "search"];

export const RESOURCES = {
  products: {
    model: "product",
    title: "Digital Products",
    singular: "Digital product",
    orderBy: [{ sort: "asc" }, { createdAt: "desc" }],
    search: ["name", "kind", "tagline", "description"],
    slugFrom: "name",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, list: true },
      { key: "image", label: "Cover image — vertical 1000×1500 (2:3) works best on Pinterest", type: "image", list: "image" },
      { key: "kind", label: "Type", type: "select", options: PRODUCT_KINDS, def: PRODUCT_KINDS[0], list: true },
      { key: "tagline", label: "Tagline (one short line under the title)", type: "text" },
      { key: "priceUsd", label: "Price ($) — international buyers. 0 = convert the ৳ price at your dollar rate", type: "decimal", def: 0, list: "usd" },
      { key: "price", label: "Price (৳) — Bangladesh buyers (bKash, Nagad...)", type: "number", required: true, list: "money" },
      { key: "gallery", label: "More preview images (shown as a gallery)", type: "gallery" },
      { key: "previewUrl", label: "Live preview link (optional) — e.g. a Canva view-only link or demo page", type: "text" },
      { key: "includes", label: "What's included (one per line)", type: "textarea" },
      { key: "description", label: "Description (start a line with - to make a bullet point)", type: "textarea", required: true },
      { key: "files", label: "Download files — private, only paying buyers can download them", type: "files" },
      { key: "deliveryText", label: "After-purchase message — only paying buyers see this (e.g. your Canva template link + how to use it)", type: "textarea" },
      { key: "sort", label: "Sort order", type: "number", def: 0 },
      { key: "featured", label: "Featured", type: "bool", list: "badge" },
      { key: "active", label: "Visible on site", type: "bool", def: true, list: "badge" },
    ],
  },
  services: {
    model: "service",
    title: "Services",
    singular: "Service",
    orderBy: [{ sort: "asc" }, { createdAt: "desc" }],
    search: ["name", "kind", "tagline", "description"],
    slugFrom: "name",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, list: true },
      { key: "image", label: "Cover image — vertical 1000×1500 (2:3) works best on Pinterest", type: "image", list: "image" },
      { key: "kind", label: "Type", type: "select", options: SERVICE_KINDS, def: SERVICE_KINDS[0], list: true },
      { key: "tagline", label: "Tagline (one short line under the title)", type: "text" },
      { key: "packages", label: "Packages", type: "packages", required: true, list: "packages" },
      { key: "gallery", label: "Portfolio images (past work)", type: "gallery" },
      { key: "description", label: "Description (start a line with - to make a bullet point)", type: "textarea", required: true },
      { key: "questions", label: "Questions the buyer answers after ordering (one per line), e.g. Your brand name? Colours you like? Links to designs you love?", type: "textarea" },
      { key: "sort", label: "Sort order", type: "number", def: 0 },
      { key: "featured", label: "Featured", type: "bool", list: "badge" },
      { key: "active", label: "Visible on site", type: "bool", def: true, list: "badge" },
    ],
  },
  tools: {
    model: "tool",
    title: "Tools",
    singular: "Tool",
    orderBy: [{ sort: "asc" }, { createdAt: "desc" }],
    search: ["name", "description"],
    slugFrom: "name",
    include: { category: true },
    fields: [
      { key: "name", label: "Name", type: "text", required: true, list: true },
      { key: "image", label: "Cover image", type: "image", list: "image" },
      { key: "categoryId", label: "Category", type: "category", list: "category" },
      { key: "price", label: "Price (৳)", type: "number", required: true, list: "money" },
      { key: "duration", label: "Duration", type: "text", def: "30 days", list: true },
      { key: "accent", label: "Cover accent color", type: "color", def: "#E8352B" },
      { key: "description", label: "Description (start a line with - to make a bullet point)", type: "textarea", required: true },
      { key: "sort", label: "Sort order", type: "number", def: 0 },
      { key: "featured", label: "Featured", type: "bool", list: "badge" },
      { key: "active", label: "Visible on site", type: "bool", def: true, list: "badge" },
      { key: "soon", label: "Coming soon", type: "soon", def: false, list: "soon" },
    ],
  },
  categories: {
    model: "category",
    title: "Categories",
    singular: "Category",
    orderBy: [{ sort: "asc" }],
    search: ["name"],
    slugFrom: "name",
    include: { _count: { select: { tools: true } } },
    fields: [
      { key: "name", label: "Name", type: "text", required: true, list: true },
      { key: "sort", label: "Sort order", type: "number", def: 0, list: true },
      { key: "active", label: "Visible", type: "bool", def: true, list: "badge" },
    ],
  },
  bundles: {
    model: "bundle",
    title: "Bundles",
    singular: "Bundle",
    orderBy: [{ sort: "asc" }],
    search: ["name", "tagline"],
    fields: [
      { key: "name", label: "Name", type: "text", required: true, list: true },
      { key: "tagline", label: "Tagline", type: "text", required: true, list: true },
      { key: "price", label: "Price (৳/month)", type: "number", required: true, list: "money" },
      { key: "icon", label: "Icon", type: "icon", def: "zap" },
      { key: "tools", label: "Included tools (one per line)", type: "textarea", required: true },
      { key: "sort", label: "Sort order", type: "number", def: 0 },
      { key: "popular", label: "Most popular", type: "bool", list: "badge" },
      { key: "active", label: "Visible", type: "bool", def: true, list: "badge" },
      { key: "soon", label: "Coming soon", type: "soon", def: false, list: "soon" },
    ],
  },
  plans: {
    model: "packPlan",
    title: "Custom Packs",
    singular: "Pack plan",
    orderBy: [{ sort: "asc" }],
    search: ["name"],
    fields: [
      { key: "name", label: "Name", type: "text", required: true, list: true },
      { key: "tagline", label: "Tagline", type: "text", required: true },
      { key: "price", label: "Price (৳/month)", type: "number", required: true, list: "money" },
      { key: "feature", label: "Feature line", type: "text", required: true, list: true },
      { key: "icon", label: "Icon", type: "icon", def: "star" },
      { key: "sort", label: "Sort order", type: "number", def: 0 },
      { key: "popular", label: "Popular", type: "bool", list: "badge" },
      { key: "active", label: "Visible", type: "bool", def: true, list: "badge" },
      { key: "soon", label: "Coming soon", type: "soon", def: false, list: "soon" },
    ],
  },
  prompts: {
    model: "prompt",
    title: "AI Prompt Vault",
    singular: "Prompt",
    orderBy: [{ sort: "asc" }, { createdAt: "desc" }],
    search: ["title", "category", "tags", "promptText"],
    slugFrom: "title",
    fields: [
      { key: "title", label: "Title", type: "text", required: true, list: true },
      { key: "image", label: "Cover image — square works best, e.g. 1080×1080 (leave empty to use a colour cover)", type: "image", list: "image" },
      { key: "accent", label: "Cover accent color (used when there is no image)", type: "color", def: "#E8352B" },
      { key: "category", label: "Category", type: "text", list: true },
      { key: "promptText", label: "The prompt (shown in the popup, with a Copy button)", type: "textarea", required: true },
      { key: "tags", label: "Works great with (comma separated, e.g. ChatGPT, Midjourney)", type: "text" },
      { key: "sort", label: "Sort order", type: "number", def: 0 },
      { key: "featured", label: "Featured", type: "bool", list: "badge" },
      { key: "active", label: "Visible on site", type: "bool", def: true, list: "badge" },
    ],
  },
  reviews: {
    model: "review",
    title: "Reviews",
    singular: "Review",
    orderBy: [{ sort: "asc" }],
    search: ["name", "text"],
    fields: [
      { key: "name", label: "Customer name", type: "text", required: true, list: true },
      { key: "source", label: "Source", type: "select", options: ["facebook", "trustpilot"], def: "facebook", list: true },
      { key: "rating", label: "Rating (1-5)", type: "number", def: 5, list: true },
      { key: "text", label: "Review", type: "textarea", required: true, list: true },
      { key: "sort", label: "Sort order", type: "number", def: 0 },
      { key: "active", label: "Visible", type: "bool", def: true, list: "badge" },
    ],
  },
  faqs: {
    model: "faq",
    title: "FAQs",
    singular: "FAQ",
    orderBy: [{ sort: "asc" }],
    search: ["question", "answer"],
    fields: [
      { key: "question", label: "Question", type: "text", required: true, list: true },
      { key: "answer", label: "Answer", type: "textarea", required: true },
      { key: "sort", label: "Sort order", type: "number", def: 0, list: true },
      { key: "active", label: "Visible", type: "bool", def: true, list: "badge" },
    ],
  },
  leads: {
    model: "lead",
    title: "Leads",
    singular: "Lead",
    orderBy: [{ createdAt: "desc" }],
    search: ["name", "email", "message"],
    noCreate: true,
    fields: [
      { key: "type", label: "Type", type: "readonly", list: true },
      { key: "name", label: "Name", type: "readonly", list: true },
      { key: "email", label: "Email", type: "readonly", list: true },
      { key: "phone", label: "Phone", type: "readonly" },
      { key: "message", label: "Message", type: "readonly", list: true },
      { key: "handled", label: "Handled", type: "bool", list: "badge" },
      { key: "createdAt", label: "Date", type: "readonly", list: "date" },
    ],
  },
  payouts: {
    model: "payout",
    title: "Payouts",
    singular: "Payout",
    orderBy: [{ createdAt: "desc" }],
    search: ["userName", "userEmail", "account"],
    noCreate: true,
    fields: [
      { key: "userName", label: "Affiliate", type: "readonly", list: true },
      { key: "userEmail", label: "Email", type: "readonly", list: true },
      { key: "amount", label: "Amount", type: "readonly", list: "money" },
      { key: "method", label: "Method", type: "readonly", list: true },
      { key: "account", label: "Account", type: "readonly", list: true },
      { key: "status", label: "Status", type: "status", options: ["PENDING", "PAID", "REJECTED"], def: "PENDING", list: "status" },
      { key: "createdAt", label: "Date", type: "readonly", list: "date" },
    ],
  },
  smmServices: {
    model: "smmService",
    title: "SMM Services",
    singular: "SMM Service",
    orderBy: [{ category: "asc" }, { sort: "asc" }],
    search: ["name", "category"],
    noCreate: true,
    fields: [
      { key: "providerServiceId", label: "Provider ID", type: "readonly", list: true },
      { key: "name", label: "Name", type: "text", required: true, list: true },
      { key: "category", label: "Category (shown on the public page)", type: "text", required: true, list: true },
      { key: "providerRate", label: "Provider cost (per 1000, USD)", type: "readonly", list: true },
      { key: "sellRate", label: "Your price (৳ per 1000)", type: "number", required: true, list: "money" },
      { key: "min", label: "Minimum quantity", type: "number", required: true, list: true },
      { key: "max", label: "Maximum quantity", type: "number", required: true, list: true },
      { key: "sort", label: "Sort order", type: "number", def: 0 },
      { key: "active", label: "Visible on site", type: "bool", def: false, list: "badge" },
    ],
  },
  walletTopups: {
    model: "walletTopup",
    title: "Wallet Topups",
    singular: "Wallet Topup",
    orderBy: [{ createdAt: "desc" }],
    search: ["userName", "userEmail", "txnId"],
    noCreate: true,
    fields: [
      { key: "userName", label: "Customer", type: "readonly", list: true },
      { key: "userEmail", label: "Email", type: "readonly", list: true },
      { key: "amount", label: "Amount", type: "readonly", list: "money" },
      { key: "method", label: "Method", type: "readonly", list: true },
      { key: "txnId", label: "Transaction ID", type: "readonly", list: true },
      { key: "status", label: "Status", type: "status", options: ["PENDING", "APPROVED", "REJECTED"], def: "PENDING", list: "status" },
      { key: "createdAt", label: "Date", type: "readonly", list: "date" },
    ],
  },
  orders: {
    model: "order",
    title: "Orders",
    singular: "Order",
    orderBy: [{ createdAt: "desc" }],
    search: ["name", "email", "phone", "itemName", "txnId"],
    noCreate: true,
    include: { smmOrder: { include: { service: true } } },
    fields: [
      { key: "number", label: "#", type: "readonly", list: "orderno" },
      { key: "itemName", label: "Item", type: "readonly", list: true },
      { key: "itemType", label: "Source", type: "readonly", list: "source" },
      { key: "amount", label: "Amount", type: "readonly", list: "money" },
      { key: "usdAmount", label: "Amount ($)", type: "readonly" },
      { key: "name", label: "Customer", type: "readonly", list: true },
      { key: "email", label: "Email", type: "readonly" },
      { key: "phone", label: "Phone", type: "readonly" },
      { key: "method", label: "Payment method", type: "readonly" },
      { key: "txnId", label: "Transaction ID", type: "readonly" },
      { key: "refCode", label: "Referred by (code)", type: "readonly" },
      { key: "commission", label: "Affiliate commission (৳)", type: "readonly" },
      { key: "status", label: "Status", type: "status", options: ["PENDING", "PAID", "IN_PROGRESS", "COMPLETED", "DELIVERED", "REFUNDED", "CANCELLED"], def: "PENDING", list: "status" },
      { key: "note", label: "Customer note", type: "readonly" },
      { key: "createdAt", label: "Date", type: "readonly", list: "date" },
    ],
  },
};

// Which permission area each table belongs to: reading needs "<area>.view", changing needs "<area>.manage"
// (orders: "orders.manage"). A table missing here is admin-only by default (needs "*").
export const RESOURCE_PERM = {
  products: "store", services: "store",
  tools: "catalog", categories: "catalog", bundles: "catalog", plans: "catalog",
  prompts: "growth", leads: "growth", smmServices: "growth",
  reviews: "content", faqs: "content",
  payouts: "affiliates", walletTopups: "affiliates",
  orders: "orders",
};
export const resourcePerm = (name, action) => (RESOURCE_PERM[name] ? `${RESOURCE_PERM[name]}.${action}` : "*");

export const NAV = [
  { href: "/admin", label: "Dashboard", icon: "dashboard" },
  { href: "/admin/orders", label: "Orders", icon: "orders" },
  { href: "/admin/sales", label: "Sales Report", icon: "sales" },
  { href: "/admin/analytics", label: "Analytics", icon: "analytics" },
  { href: "/admin/affiliates", label: "Affiliates", icon: "affiliates" },
  { href: "/admin/payouts", label: "Payouts", icon: "payouts" },
  { href: "/admin/wallet-topups", label: "Wallet Topups", icon: "wallet" },
  { href: "/admin/free-offers", label: "Free Offers", icon: "offers" },
  { href: "/admin/smm-services", label: "SMM Panel", icon: "smm" },
  { href: "/admin/smm-report", label: "SMM Panel Report", icon: "smmReport" },
  { href: "/admin/prompts", label: "AI Prompt Vault", icon: "prompts" },
  { href: "/admin/leads", label: "Leads", icon: "leads" },
  { href: "/admin/products", label: "Digital Products", icon: "products" },
  { href: "/admin/services", label: "Services", icon: "services" },
  { href: "/admin/tools", label: "Tools", icon: "tools" },
  { href: "/admin/tool-limits", label: "Tool Limits", icon: "limits" },
  { href: "/admin/categories", label: "Categories", icon: "categories" },
  { href: "/admin/bundles", label: "Bundles", icon: "bundles" },
  { href: "/admin/plans", label: "Custom Packs", icon: "plans" },
  { href: "/admin/reviews", label: "Reviews", icon: "reviews" },
  { href: "/admin/faqs", label: "FAQs", icon: "faqs" },
  { href: "/admin/content", label: "Page Content", icon: "content" },
  { href: "/admin/settings", label: "Settings", icon: "settings" },
  { href: "/admin/team", label: "Team & Roles", icon: "team" },
];
